//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compny_Task.Dbcontex
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Emp_Table
    {
        public int ID { get; set; }
        public string EmpNO { get; set; }
        public string EmpName { get; set; }
        public string PhoneNo { get; set; }
        public string Salary { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string Emp_Photo { get; set; }
        public string PhotoPath { get; set; }
        public string Qualification { get; set; }
        public HttpPostedFileBase Imagefile { get; set; }

    }
}
